### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [wthompson92/mod_0_skills#1]
# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

#### Part II: Top Down Design

- [x] I broke down larger processes smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a verb and a capital letter.
- [x] I pushed my changes to Github. 

#### Part III: Classes in a System

- [x] I structured and named my directories and files correctly.
- [ ] The attributes I chose for **Class #1** represent states or characteristics.
- [ ] The attributes I chose for **Class #2** represent states or characteristics.
- [ ] The attributes I chose for **Class #3** represent states or characteristics.
- [ ] The methods I chose for **Class #1** represent behaviors or actions.
- [ ] The methods I chose for **Class #2** represent behaviors or actions.
- [ ] The methods I chose for **Class #3** represent behaviors or actions.
- [ ] I identified the data type (string, integer, boolean, array, hash/object, datetime) for each attribute in all three classes.
- [ ] I added and committed each class addition **separately** with a properly formatted commit message. 
- [x] I pushed my changes to Github. 

### Notes

> For classes in the restaurant app, think of actual real-life things `Food` or `User` or `Drink`, etc. In general, classes are going to map pretty closely with their real-life counterpart. Make sure that your attributes apply to one specific instance of that thing. 
> For example, in a `Restaurant` class, you wouldn't have attributes like `List of Restaurants` or `Number of Restaurants` since one instance of a restaurant wouldn't have a list of restaurants. Here's what a Restaurant class might look like:

```
Restaurant

Attributes:
manager_name (string)
hours_of_operation (hash)
established_date (datetime)
address (string)
menu (array)

Methods:
add_new_menu_item (adds an item to the menu array)
years_in_operation (subtracts established date from current year)
replace_manager (changes manager_name attribute to new name)
```
> All of the attributes and methods define what is possible for a single restaurant. Keep that in mind for classes. 
> It looks like you have a `first commit` and an `Initial commit` -- do you know how that might have happened? 
> For the rest of your commits, make sure that it's clear what took place in that commit. For example, instead of `Add content` (which is hard to know what content your adding to what file), use something like `Break down process of ordering food in restaurant`

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

> We want you to try this slightly different challenge below, focusing on the comments from the notes section:

##### Part I
1. Use your terminal to create a directory called `mod_0_skills_take_2`.
1. Inside of that folder, create four files: `class_1.txt`, `class_1_example_object.txt`, `class_2.txt`, and `class_2_example_object.txt`. *(If you're comfortable trying markdown at this point, feel free to use .md instead of .txt).*
1. Initialize `mod_0_skills` as a git repository.
1. Add all four empty files to the staging area and commit using the message "Initial commit"
1. Create a public repo on Github with the same name (`mod_0_skills_take_2`).
1. Add the remote and push your local repository to Github.

#### Part II
1. Open up `class_1.txt` in your text editor.
1. Brainstorm one class that might exist in a **school** and put this at the top of the file.
1. List at least three attributes for that class. In parentheses, list the data type for that attribute (string, boolean, integer, float, hash/object, datetime).
1. List at least three methods for that class. In parentheses, explain what the method does, including the names of the attributes that it uses or modifies.
1. Save your file.
1. Add and commit your changes for this class using a clear commit message. 
1. Open up `class_1_example_object.txt` in your text editor.
1. At the top, type the name of an object that is an instance of your class.
1. List the values for each attribute.
1. List the results of the method being called for this specific object.
1. Save your file.
1. Add and commit your changes for this class using a clear commit message.
1. Repeat steps 2-6 with `class_2.txt`.
1. Repeat steps 7-12 with `class_2_example_object.txt`.
1. Push your changes to GitHub.
